from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(613, 583)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.friends_tab = QtWidgets.QPushButton(self.centralwidget)
        self.friends_tab.setGeometry(QtCore.QRect(60, 490, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.friends_tab.setFont(font)
        self.friends_tab.setObjectName("friends_tab")
        self.events_tab = QtWidgets.QPushButton(self.centralwidget)
        self.events_tab.setGeometry(QtCore.QRect(240, 490, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.events_tab.setFont(font)
        self.events_tab.setObjectName("events_tab")
        self.noti_tab = QtWidgets.QPushButton(self.centralwidget)
        self.noti_tab.setGeometry(QtCore.QRect(420, 490, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.noti_tab.setFont(font)
        self.noti_tab.setObjectName("noti_tab")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 20, 561, 461))
        self.stackedWidget.setObjectName("stackedWidget")
        self.events = QtWidgets.QWidget()
        self.events.setObjectName("events")
        self.event_title = QtWidgets.QLabel(self.events)
        self.event_title.setGeometry(QtCore.QRect(10, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.event_title.setFont(font)
        self.event_title.setIndent(1)
        self.event_title.setObjectName("event_title")
        self.stackedWidget.addWidget(self.events)
        self.login1 = QtWidgets.QWidget()
        self.login1.setObjectName("login1")
        self.username = QtWidgets.QLineEdit(self.login1)
        self.username.setGeometry(QtCore.QRect(190, 80, 151, 20))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.login1)
        self.password.setGeometry(QtCore.QRect(190, 130, 151, 20))
        self.password.setObjectName("password")
        self.unamelabel = QtWidgets.QLabel(self.login1)
        self.unamelabel.setGeometry(QtCore.QRect(90, 70, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.unamelabel.setFont(font)
        self.unamelabel.setIndent(1)
        self.unamelabel.setObjectName("unamelabel")
        self.loginbutton = QtWidgets.QPushButton(self.login1)
        self.loginbutton.setGeometry(QtCore.QRect(230, 200, 75, 23))
        self.loginbutton.setObjectName("loginbutton")
        self.pwordlabel = QtWidgets.QLabel(self.login1)
        self.pwordlabel.setGeometry(QtCore.QRect(90, 120, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pwordlabel.setFont(font)
        self.pwordlabel.setIndent(1)
        self.pwordlabel.setObjectName("pwordlabel")
        self.stackedWidget.addWidget(self.login1)
        self.friends = QtWidgets.QWidget()
        self.friends.setObjectName("friends")
        self.flist_title = QtWidgets.QLabel(self.friends)
        self.flist_title.setGeometry(QtCore.QRect(10, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.flist_title.setFont(font)
        self.flist_title.setIndent(1)
        self.flist_title.setObjectName("flist_title")
        self.stackedWidget.addWidget(self.friends)
        self.notifications = QtWidgets.QWidget()
        self.notifications.setObjectName("notifications")
        self.noti_title = QtWidgets.QLabel(self.notifications)
        self.noti_title.setGeometry(QtCore.QRect(10, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.noti_title.setFont(font)
        self.noti_title.setIndent(1)
        self.noti_title.setObjectName("noti_title")
        self.stackedWidget.addWidget(self.notifications)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 613, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.friends_tab.setText(_translate("MainWindow", "Friends"))
        self.events_tab.setText(_translate("MainWindow", "Events"))
        self.noti_tab.setText(_translate("MainWindow", "Notifications"))
        self.event_title.setText(_translate("MainWindow", "Events:"))
        self.unamelabel.setText(_translate("MainWindow", "Username: "))
        self.loginbutton.setText(_translate("MainWindow", "Log in"))
        self.pwordlabel.setText(_translate("MainWindow", "Password: "))
        self.flist_title.setText(_translate("MainWindow", "Friends List:"))
        self.noti_title.setText(_translate("MainWindow", "Notifications:"))
